export const INCREASE_COUNTER = "INCREASE_COUNTER";
export const DECREASE_COUNTER = "DECREASE_COUNTER";
export const INCREASE_BY_TWO = "INCREASE_BY_TWO";
export const DECREASE_BY_TWO = "DECREASE_BY_TWO";
